fixed concourse startup script

diff --git a/images/bastion/bin/common b/images/bastion/bin/common
--- a/images/bastion/bin/common
+++ b/images/bastion/bin/common
@@ -17,6 +17,26 @@ function parse_yaml {
    }'
 }
 
+function wait_for_url {
+    local name=$1
+    local url=$2
+
+    i=0
+    curl -f -L "$url" >/dev/null 2>&1
+    while [[ $? -ne 0 && $i -lt 12 ]]; do
+        
+        i=$(($i+1))
+        echo "Waiting for $name to startup..."
+        sleep 5
+
+        curl -f -L "$url" >/dev/null 2>&1
+    done
+    if [[ $? -ne 0 ]]; then 
+        echo "ERROR! $name is still not running after 60 seconds."
+        exit 1
+    fi
+}
+
 # This script needs to be run as root
 if [[ `whoami` != "root" ]]; then 
     echo -e "\nThis script needs to be run as root.\n"
